language: node_js
node_js:
- '4'
services:
- mongodb
- docker
env:
  DOCKER_EMAIL:
    secure: Pbbiz386Nb0Vh4sXWayTTXOsccGhE7HljmsmD955yAF08A+gQiLpoQLHH3lMPU35NqoRvvKhaz/uMESEsBHGOIoq/aRIH3cdQse9I/hj1a5EZa8jNOdxu1CxJhHjAC5tHAcsIkXjqZdYdx2TO5IcrRF71+BO2UiJeDJsz6lqE5S30CLEh3LCCyY63qAC7I1T6ZtVruZW+T954/sz3/S4QCCMC9F1nKxIb0CZLxtBKvOLS/1RadOgJfj3p2AipZOF97voOi5y2ioshWl/R6+LmDDFQjH2nwaFpNRp6YKFfozfHLfbxlv42Mm8pDcpRZkX/zwQ0Gvf2YmoP96yPyg/hNbsrjX7fqpjW8wn2kGrceVHwEYcvOQAfHMmrQQbeDUZWcrKYFnboEG4uUDKpDrhd/BJCye43JNgMZeUYwegaCtwAQYRF1SILDU4RRgINrvOQTexgYvHJDEuj09szVoRLz6TWTzEcP+5mIKUER5Y4P18XiswENYaDKf+GBADbP6eLIPP4JPgEPreo4iucqSenoiZtW4vnRVbCuMLjLKO+LpFbl616mo7NyjurwbeAewAIcEH9o+jK3NFiCP/xMv1Lg+HpbpDhuXXGvIXG/RMHorYscQ/JB+ikU5OzeCMtMa99j5BKX1r586S2ryW4p4JljPEbpFVLGSa9RSrpRoUQF4=
  DOCKER_USER:
    secure: QXFEwLxvwI2OusJPUAMCnDyGA8hIrjSZN6Y9JojlxTHjac6uBK+O1uylnxujO0Zq3rxAWCi4Qp9qDsd0LJYumIZ/jMDKw6+wzbGklJv2Wu7LZvlNaiMKv0HHLAEVgQQJmq4pVzCCQLa8AKZsj6hEQd5IW8opHlMQuDonolkhIFWxYVGwntR/ycntbaQqqt49VqeT+WE8wSczVVVdi8RQGN3sDtbtuaXJpYhoori7CgT5l5KmAeWVsv/RfXYO+WIxn2pLoUVfwPX6dx/jakuw9qf7Pj5EXjJLDBYxzJbMDT8cjGf7bJHKx8zTX5p2d83izSfOxaGpVUjYjQCnESaFKWGKzVRkHU3yw61ylBWIl1CCERa9Jo7G6SOYTRthKYP2nG8Vi6+0OHaiXKqNTd1y/OI6naOvDuElvt45VmL5aDHrL/yG2MWrNFBPsEmdxkEnB0H5A9Ksa58zxQjGc0vKDdbTh1Fa8HnXS6tAGjEgRJoD0N1BaeTMSKI4GGygwfTF3DiVwkBP/TjtwqgfgteCnBeuU3KHA701x4T84FiaLfZVLWkRiLD+ks1fp7b+fQ52qJuv9axvI4blAG/Qe+I7qYLecsksyCsXuu/qiL13blzcNmw9A+bZGvzRYBX4lDOwzgkofmeXu2W0L50QfZT0Xy+l9Yq9GMPNrH3px+AxWSs=
  DOCKER_PASS:
    secure: alBdKvj3tEVCKof4Fxh0sNlYkbOce4dUTP33Y6XC2R3B875SWqOuPSrV48ClC63NwvGyq3Z8bFNgfIktLlOBeh/mxhhwRxFK5MLTYL64cASSpDS6lkuEszX1vI663tRP/ACkOqS5gAPJMu2m+cKffFEfB63FhwvVYTTKa2VjNzzBfMOSnGhNXwz1KKPdigPblnPw+X9K+/P3/HBc2uzdtBDlOzNnlZdKvluL63JWlDoqxBSOnh7I/7wDV5dB4rlPDUxMw3YGGdDh45GyLU9uPKE8MgAjYV4aOr2gN84tk7TUzVjeOuaNwrUAGER2cxaomvkJrfXFDhj03aPF53GsoaAJJ+Fu8YuH8kgi9WMjd3x8nTC6H6TN+x7iiBwpbq9WI3DVaUZuiRrHpVG/8oy6tZnVvhnxZhX3S6KdbZO3YxId8DmWKJfitqudNC1eOQmrUB2TOg3DuytvJYR4n8HA1hw47ehSUlasGn3hiSCTeonQ/O1Jatc8RL796vPosPoNvKPefu/1jg+H/gvIikSJIioGMJ58ROSW9Uf/qeseWnUBAwooNZ5p9N3wGs7gbcgSEiONcA54OErczIxxPx23+QksL0YkUx/Jj/zc152ZwgAK24nToIE30U4Dzgy1fNYtsBVvI0JSPQ5Gk3ZC68k1NEKT8esQz3dJ3z7ZhjEc4oY=

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/k-auth
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
