version: '2'
services:
  auth:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "3090:3090"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - auth_mongodata
  auth_mongodata:
    image: tianon/true
    volumes:
      - /data/db
